/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanicButtonIndexRouteImport } from './routes/panic-button.index'
import { Route as GamePlanIndexRouteImport } from './routes/game-plan.index'
import { Route as GamePlanTypeRouteImport } from './routes/game-plan.$type'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicButtonIndexRoute = PanicButtonIndexRouteImport.update({
  id: '/panic-button/',
  path: '/panic-button/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlanIndexRoute = GamePlanIndexRouteImport.update({
  id: '/game-plan/',
  path: '/game-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlanTypeRoute = GamePlanTypeRouteImport.update({
  id: '/game-plan/$type',
  path: '/game-plan/$type',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plan/': typeof GamePlanIndexRoute
  '/panic-button/': typeof PanicButtonIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plan': typeof GamePlanIndexRoute
  '/panic-button': typeof PanicButtonIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plan/': typeof GamePlanIndexRoute
  '/panic-button/': typeof PanicButtonIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/game-plan/$type' | '/game-plan/' | '/panic-button/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/game-plan/$type' | '/game-plan' | '/panic-button'
  id: '__root__' | '/' | '/game-plan/$type' | '/game-plan/' | '/panic-button/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamePlanTypeRoute: typeof GamePlanTypeRoute
  GamePlanIndexRoute: typeof GamePlanIndexRoute
  PanicButtonIndexRoute: typeof PanicButtonIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic-button/': {
      id: '/panic-button/'
      path: '/panic-button'
      fullPath: '/panic-button/'
      preLoaderRoute: typeof PanicButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plan/': {
      id: '/game-plan/'
      path: '/game-plan'
      fullPath: '/game-plan/'
      preLoaderRoute: typeof GamePlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plan/$type': {
      id: '/game-plan/$type'
      path: '/game-plan/$type'
      fullPath: '/game-plan/$type'
      preLoaderRoute: typeof GamePlanTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamePlanTypeRoute: GamePlanTypeRoute,
  GamePlanIndexRoute: GamePlanIndexRoute,
  PanicButtonIndexRoute: PanicButtonIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
