/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerInfoIndexRouteImport } from './routes/player-info.index'
import { Route as PanicButtonIndexRouteImport } from './routes/panic-button.index'
import { Route as GamePlanIndexRouteImport } from './routes/game-plan.index'
import { Route as GamePlansSplatRouteImport } from './routes/game-plans.$'
import { Route as GamePlanTypeRouteImport } from './routes/game-plan.$type'
import { Route as ApiPublicCardEventRouteImport } from './routes/api/public/card-event'
import { Route as ApiKioskPlayerInfoRouteImport } from './routes/api/kiosk.player-info'
import { Route as ApiKioskHealthRouteImport } from './routes/api/kiosk.health'
import { Route as ApiCardStreamRouteImport } from './routes/api/card.stream'
import { Route as ApiKioskPlayerImagePlayerIdRouteImport } from './routes/api/kiosk.player-image.$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerInfoIndexRoute = PlayerInfoIndexRouteImport.update({
  id: '/player-info/',
  path: '/player-info/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanicButtonIndexRoute = PanicButtonIndexRouteImport.update({
  id: '/panic-button/',
  path: '/panic-button/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlanIndexRoute = GamePlanIndexRouteImport.update({
  id: '/game-plan/',
  path: '/game-plan/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlansSplatRoute = GamePlansSplatRouteImport.update({
  id: '/game-plans/$',
  path: '/game-plans/$',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePlanTypeRoute = GamePlanTypeRouteImport.update({
  id: '/game-plan/$type',
  path: '/game-plan/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCardEventRoute = ApiPublicCardEventRouteImport.update({
  id: '/api/public/card-event',
  path: '/api/public/card-event',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskPlayerInfoRoute = ApiKioskPlayerInfoRouteImport.update({
  id: '/api/kiosk/player-info',
  path: '/api/kiosk/player-info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskHealthRoute = ApiKioskHealthRouteImport.update({
  id: '/api/kiosk/health',
  path: '/api/kiosk/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCardStreamRoute = ApiCardStreamRouteImport.update({
  id: '/api/card/stream',
  path: '/api/card/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKioskPlayerImagePlayerIdRoute =
  ApiKioskPlayerImagePlayerIdRouteImport.update({
    id: '/api/kiosk/player-image/$playerId',
    path: '/api/kiosk/player-image/$playerId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plans/$': typeof GamePlansSplatRoute
  '/game-plan/': typeof GamePlanIndexRoute
  '/panic-button/': typeof PanicButtonIndexRoute
  '/player-info/': typeof PlayerInfoIndexRoute
  '/api/card/stream': typeof ApiCardStreamRoute
  '/api/kiosk/health': typeof ApiKioskHealthRoute
  '/api/kiosk/player-info': typeof ApiKioskPlayerInfoRoute
  '/api/public/card-event': typeof ApiPublicCardEventRoute
  '/api/kiosk/player-image/$playerId': typeof ApiKioskPlayerImagePlayerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plans/$': typeof GamePlansSplatRoute
  '/game-plan': typeof GamePlanIndexRoute
  '/panic-button': typeof PanicButtonIndexRoute
  '/player-info': typeof PlayerInfoIndexRoute
  '/api/card/stream': typeof ApiCardStreamRoute
  '/api/kiosk/health': typeof ApiKioskHealthRoute
  '/api/kiosk/player-info': typeof ApiKioskPlayerInfoRoute
  '/api/public/card-event': typeof ApiPublicCardEventRoute
  '/api/kiosk/player-image/$playerId': typeof ApiKioskPlayerImagePlayerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/game-plan/$type': typeof GamePlanTypeRoute
  '/game-plans/$': typeof GamePlansSplatRoute
  '/game-plan/': typeof GamePlanIndexRoute
  '/panic-button/': typeof PanicButtonIndexRoute
  '/player-info/': typeof PlayerInfoIndexRoute
  '/api/card/stream': typeof ApiCardStreamRoute
  '/api/kiosk/health': typeof ApiKioskHealthRoute
  '/api/kiosk/player-info': typeof ApiKioskPlayerInfoRoute
  '/api/public/card-event': typeof ApiPublicCardEventRoute
  '/api/kiosk/player-image/$playerId': typeof ApiKioskPlayerImagePlayerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/game-plan/$type'
    | '/game-plans/$'
    | '/game-plan/'
    | '/panic-button/'
    | '/player-info/'
    | '/api/card/stream'
    | '/api/kiosk/health'
    | '/api/kiosk/player-info'
    | '/api/public/card-event'
    | '/api/kiosk/player-image/$playerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/game-plan/$type'
    | '/game-plans/$'
    | '/game-plan'
    | '/panic-button'
    | '/player-info'
    | '/api/card/stream'
    | '/api/kiosk/health'
    | '/api/kiosk/player-info'
    | '/api/public/card-event'
    | '/api/kiosk/player-image/$playerId'
  id:
    | '__root__'
    | '/'
    | '/game-plan/$type'
    | '/game-plans/$'
    | '/game-plan/'
    | '/panic-button/'
    | '/player-info/'
    | '/api/card/stream'
    | '/api/kiosk/health'
    | '/api/kiosk/player-info'
    | '/api/public/card-event'
    | '/api/kiosk/player-image/$playerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamePlanTypeRoute: typeof GamePlanTypeRoute
  GamePlansSplatRoute: typeof GamePlansSplatRoute
  GamePlanIndexRoute: typeof GamePlanIndexRoute
  PanicButtonIndexRoute: typeof PanicButtonIndexRoute
  PlayerInfoIndexRoute: typeof PlayerInfoIndexRoute
  ApiCardStreamRoute: typeof ApiCardStreamRoute
  ApiKioskHealthRoute: typeof ApiKioskHealthRoute
  ApiKioskPlayerInfoRoute: typeof ApiKioskPlayerInfoRoute
  ApiPublicCardEventRoute: typeof ApiPublicCardEventRoute
  ApiKioskPlayerImagePlayerIdRoute: typeof ApiKioskPlayerImagePlayerIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-info/': {
      id: '/player-info/'
      path: '/player-info'
      fullPath: '/player-info/'
      preLoaderRoute: typeof PlayerInfoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panic-button/': {
      id: '/panic-button/'
      path: '/panic-button'
      fullPath: '/panic-button/'
      preLoaderRoute: typeof PanicButtonIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plan/': {
      id: '/game-plan/'
      path: '/game-plan'
      fullPath: '/game-plan/'
      preLoaderRoute: typeof GamePlanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plans/$': {
      id: '/game-plans/$'
      path: '/game-plans/$'
      fullPath: '/game-plans/$'
      preLoaderRoute: typeof GamePlansSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game-plan/$type': {
      id: '/game-plan/$type'
      path: '/game-plan/$type'
      fullPath: '/game-plan/$type'
      preLoaderRoute: typeof GamePlanTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/card-event': {
      id: '/api/public/card-event'
      path: '/api/public/card-event'
      fullPath: '/api/public/card-event'
      preLoaderRoute: typeof ApiPublicCardEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/player-info': {
      id: '/api/kiosk/player-info'
      path: '/api/kiosk/player-info'
      fullPath: '/api/kiosk/player-info'
      preLoaderRoute: typeof ApiKioskPlayerInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/health': {
      id: '/api/kiosk/health'
      path: '/api/kiosk/health'
      fullPath: '/api/kiosk/health'
      preLoaderRoute: typeof ApiKioskHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/card/stream': {
      id: '/api/card/stream'
      path: '/api/card/stream'
      fullPath: '/api/card/stream'
      preLoaderRoute: typeof ApiCardStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kiosk/player-image/$playerId': {
      id: '/api/kiosk/player-image/$playerId'
      path: '/api/kiosk/player-image/$playerId'
      fullPath: '/api/kiosk/player-image/$playerId'
      preLoaderRoute: typeof ApiKioskPlayerImagePlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamePlanTypeRoute: GamePlanTypeRoute,
  GamePlansSplatRoute: GamePlansSplatRoute,
  GamePlanIndexRoute: GamePlanIndexRoute,
  PanicButtonIndexRoute: PanicButtonIndexRoute,
  PlayerInfoIndexRoute: PlayerInfoIndexRoute,
  ApiCardStreamRoute: ApiCardStreamRoute,
  ApiKioskHealthRoute: ApiKioskHealthRoute,
  ApiKioskPlayerInfoRoute: ApiKioskPlayerInfoRoute,
  ApiPublicCardEventRoute: ApiPublicCardEventRoute,
  ApiKioskPlayerImagePlayerIdRoute: ApiKioskPlayerImagePlayerIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
